version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.chainguard
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:Z
      - ./data/chromadb:/app/data/chromadb:Z
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHROMA_PERSIST_DIRECTORY=/app/data/chromadb
    depends_on:
      - redis
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/data/chromadb
    user: nonroot

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.chainguard
    command: ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info"]
    volumes:
      - ./backend:/app:Z
      - ./data/chromadb:/app/data/chromadb:Z
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHROMA_PERSIST_DIRECTORY=/app/data/chromadb
    depends_on:
      - redis
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/data/chromadb
    user: nonroot

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.chainguard
    command: ["celery", "-A", "app.core.celery_app", "beat", "--loglevel=info"]
    volumes:
      - ./backend:/app:Z
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    user: nonroot

  redis:
    image: cgr.dev/chainguard/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:Z
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    user: nonroot

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.chainguard
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:Z
      - node_modules:/app/node_modules:Z
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    user: nonroot

volumes:
  redis_data:
    driver: local
  node_modules:
    driver: local
